version: '3.8'

services:

  main:
    image: ${DOCKER_DOMAIN}/${PROJECT_NAME}-docker:${RELEASE}.local

    extends:
      file: ${BASE_SERVICE_FILENAME}
      service: ${BASE_SERVICE_NAME}

    environment:
        - PROJECT_NAME=${PROJECT_NAME}
        - RELEASE=${RELEASE}
        - ICUB_SIMULATION=true
        - ICUB_NAME=icubSim
        - ICUB_USER=icub
        - ICUB_PSW=icub
        - ICUB_HOST=pc104
        - ICUB_APPS=${WORKDIR}/shared/icub/applications

    command: ["/bin/bash", "-c", "terminator & bash /home/docky/init.sh"]

    volumes:
      - type: bind
        source: ./pyicub
        target: ${WORKDIR}/pyicub
