services:
  pyicub:
    container_name: pyicub
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DOCKER_SRC: ${ROBOTOLOGY_IMAGE_NAME} 
    image: ${PYICUB_IMAGE_NAME}
    gpus: all
    command: ["/bin/bash", "-c", "terminator & bash /var/scripts/initContainer.sh"]
    environment:
      - DISPLAY=${DISPLAY:?err}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR:?err}/pulse/native
      - PULSE_COOKIE=/run/pulse/cookie
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:?err}
      - XDG_DATA_DIRS=${XDG_DATA_DIRS:?err}
      - QT_X11_NO_MITSHM=1
      - NO_AT_BRIDGE=1
      - LIBGL_ALWAYS_SOFTWARE=false
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    env_file:
      - .env
    working_dir: /workdir
    privileged: true
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ${HOME}/.config/pulse/cookie
        target: /run/pulse/cookie
      - type: bind
        source: ${XDG_RUNTIME_DIR:?err}/pulse
        target: ${XDG_RUNTIME_DIR:?err}/pulse
      - type: bind
        source: ${XDG_RUNTIME_DIR:?err}/dconf
        target: ${XDG_RUNTIME_DIR:?err}/dconf
      - type: bind
        source: ./scripts
        target: /var/scripts
      - type: bind
        source: ./workdir
        target: /workdir

    profiles: ["backend"]

  pyicub-frontend:
    container_name: pyicub-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${PYICUB_FRONTEND_IMAGE_NAME}
    network_mode: host
    depends_on:
      - pyicub
    profiles: ["frontend"]

  pyicub-test:
    image: ${PYICUB_IMAGE_NAME}
    gpus: all
    command: ["/bin/bash", "-c", "bash /var/scripts/runTests.sh"]
    environment:
      - DISPLAY=${DISPLAY:?err}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR:?err}/pulse/native
      - PULSE_COOKIE=/run/pulse/cookie
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:?err}
      - XDG_DATA_DIRS=${XDG_DATA_DIRS:?err}
      - QT_X11_NO_MITSHM=1
      - NO_AT_BRIDGE=1
      - LIBGL_ALWAYS_SOFTWARE=false
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    env_file:
      - .env
    privileged: true
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ${HOME}/.config/pulse/cookie
        target: /run/pulse/cookie
      - type: bind
        source: ${XDG_RUNTIME_DIR:?err}/pulse
        target: ${XDG_RUNTIME_DIR:?err}/pulse
      - type: bind
        source: ${XDG_RUNTIME_DIR:?err}/dconf
        target: ${XDG_RUNTIME_DIR:?err}/dconf
      - type: bind
        source: ./scripts
        target: /var/scripts
      - type: bind
        source: ./workdir
        target: /workdir
  
    profiles: ["test"]

