version: '3.7'

services:

  pyicub:

    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_SRC: iitschri/icub:${ICUB_DISTRO}
        PYICUB_TAG: ${PYICUB_TAG}

    image: iitschri/pyicub:${PYICUB_TAG}-${ICUB_DISTRO}

    command: init.sh ${SIMULATION} ${ICUB_USER} ${ICUB_PSW} ${ICUB_HOSTNAME} ${APPS}

    environment:
      - "DISPLAY=${DISPLAY}"
      - "XAUTHORITY=${HOME}/.Xauthority"

    privileged: true
    stdin_open: true
    tty: true

    network_mode: "host"

    volumes:
      - type: bind
        source: ../
        target: /home/docky/pyicub

      - type: bind
        source: ${XAUTHORITY}
        target: /${HOME}/.Xauthority

      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
