version: '3.9'

services:

  pyicub-app:

    build:
      context: .
      dockerfile: Dockerfile
      args:
        SRC_IMAGE: iitschri/pyicub:${PYICUB_TAG}-${ICUB_DISTRO}
        LOCAL_USER_ID: ${LOCAL_USER_ID}
    container_name: pyicub-app

    command: init.sh ${SIMULATION} ${ICUB_USER} ${ICUB_PSW} ${ICUB_HOSTNAME} ${APPS}

    environment:
      - "DISPLAY=${DISPLAY}"
      - "XAUTHORITY=${HOME}/.Xauthority"

    privileged: true
    stdin_open: true
    tty: true

    network_mode: "host"

    volumes:

      - type: bind
        source: ${XAUTHORITY}
        target: /${HOME}/.Xauthority

      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix

      - type: bind
        source: ./
        target: /home/docky/pyicub/apps
