name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies (Graphviz)
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz graphviz-dev libgraphviz-dev

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install sphinx sphinx-rtd-theme
          pip install -r requirements.txt
          pip install -e .
          echo "Python Packages Installed:"
          pip list

      - name: Verify Sphinx Installation
        run: |
          sphinx-build --version

      - name: Build Sphinx documentation
        run: |
          sphinx-apidoc -o docs/source pyicub  
          sphinx-build -b html docs/source docs/build/html -D html_static_path=docs/static -D html_extra_path=docs/extras -D autosummary_generate=True

      - name: Rename autosummary and sources folders
        run: |
          mv docs/build/html/_autosummary docs/build/html/autosummary
          mv docs/build/html/_sources docs/build/html/sources

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to the gh-pages branch
          folder: docs/build/html  # Directory containing the generated HTML
          clean: true  # Remove old files before deploying
